/**
 * Date-ideas SEO cluster — supports pillar /blog/50-best-date-ideas-austin
 */
import type { BlogPost } from "./blog";

const PILLAR = { href: "/blog/50-best-date-ideas-austin", text: "50 best date ideas in Austin", external: false as const };
const BOOKING = { href: "/booking", text: "Book your Lake Austin experience", external: false as const };
const SUNSET = { href: "/experiences/sunset", text: "Lake Austin sunset cruise", external: false as const };
const PONTOON = { href: "/experiences/lake-austin-pontoon", text: "Lake Austin pontoon rental", external: false as const };
const AUSTIN_RENTAL = { href: "/austin-boat-rental", text: "Austin boat rental guide", external: false as const };

export const dateIdeasClusterPosts: BlogPost[] = [
  // #21 — Highest booking potential (full brief)
  {
    slug: "how-to-propose-on-a-boat-austin",
    title: "How to Propose on a Boat in Austin: The Complete Guide for Lake Austin Proposals",
    excerpt:
      "Planning a boat proposal in Austin? Here's exactly how to pull it off on Lake Austin — from choosing the right moment to booking a private charter with Boat Bros ATX.",
    date: "2026-05-20",
    author: "Boat Bros",
    image: "/photos/IMG_9647%202.webp",
    imageAlt: "Couple on a Lake Austin boat at sunset — romantic proposal setting",
    category: "general",
    readingTimeMinutes: 11,
    seoKeywords: [
      "how to propose on a boat",
      "boat proposal Austin",
      "Lake Austin proposal",
      "romantic boat proposal ideas",
      "Austin engagement on water",
    ],
    keyTakeaways: [
      "A Lake Austin boat proposal combines privacy, scenery, and zero crowd pressure — if you plan the timing and route with your captain.",
      "Book a private captained charter (not a crowded public tour) so you control the moment, music, and where you drop anchor.",
      "Coordinate with your captain beforehand: where to kneel, when to cue photos, and a backup plan if weather shifts.",
      "Keep the ring secure in a zippered pocket or case — not loose in a swim bag — and tell one trusted friend on board if you have a photographer.",
      "Boat Bros private charters are built for proposals; we'll help you plan the route, timing, and surprise without spoiling it.",
    ],
    faqs: [
      { q: "Is proposing on a boat in Austin a good idea?", a: "Yes — Lake Austin offers calm water, Hill Country views, and privacy you won't get at a crowded overlook. A captained private charter means you focus on the moment while your captain handles navigation and timing." },
      { q: "What time of day is best for a Lake Austin boat proposal?", a: "Golden hour before sunset is the most popular: dramatic light, cooler temperatures, and a natural emotional peak. Your captain can suggest departure times based on season — summer sunsets run later than spring." },
      { q: "Do I need to rent the whole boat for a proposal?", a: "For a proposal, a private captained charter is strongly recommended so it's just your group (and crew). Shared sunset cruises work for dates but aren't ideal when you're asking someone to marry you." },
      { q: "What if the weather is bad on proposal day?", a: "Have a backup date or a land-based plan your captain can pivot to (scenic cruise without anchoring, or reschedule). Book with an operator who communicates clearly about weather policies." },
      { q: "Can Boat Bros help plan a proposal on Lake Austin?", a: "Yes. Tell us when you book that it's a proposal — we'll help with route, timing, and discretion so your partner doesn't catch on early." },
    ],
    body: [
      { type: "p", content: "A boat proposal on Lake Austin hits different than a restaurant or a crowded overlook: you're surrounded by water and sky, there's no audience behind you, and the moment feels cinematic without trying too hard. If you're nervous about getting it wrong, you're not alone — most people have never planned a proposal on water. This guide walks you through exactly how to propose on a boat in Austin, from picking the charter to the second you drop to one knee. For the full list of romantic Austin ideas, see our [50 best date ideas in Austin](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "Why a Lake Austin Boat Proposal Works" },
      { type: "p", content: "Lake Austin is a constant-level reservoir minutes from downtown — not a three-hour drive to a crowded lake. That means you can build a whole day (brunch, boat, dinner) without logistics eating the romance. The water is calm enough for a steady boat, the hills give you a backdrop that photographs beautifully, and a [private captained charter](/austin-boat-rental) keeps the guest list to people you choose. Compare that to public proposal spots where strangers film you on their phones." },
      { type: "h2", content: "Step 1: Choose the Right Boat Experience" },
      { type: "p", content: "Not every boat rental is proposal-ready. You want a **private captained charter** — not a packed party pontoon with strangers. Private means you control music, route, and who is on board. Captained means you're not driving while your hands are shaking. [Boat Bros private charters](/booking) are designed for milestones like this; tell us when you book and we'll plan around your surprise." },
      { type: "h3", content: "Sunset cruise vs. private charter for a proposal" },
      { type: "p", content: "A [sunset cruise](/experiences/sunset) is perfect for a date night; for a proposal, most couples book a private charter so it's only your group (plus captain). You can still time it for golden hour — that's when Lake Austin looks its best. If budget is tight, ask about shorter private slots; the moment matters more than a four-hour rental." },
      { type: "h2", content: "Step 2: Plan the Moment With Your Captain" },
      { type: "p", content: "The biggest mistake is winging it on the water. A week before, confirm: where you'll anchor or slow down, what time the sun sets, whether you'll have a photographer or friend on board, and a signal for \"now\" (song change, route to a cove, etc.). Captains know the quiet stretches near the dam and mid-lake coves that feel private. Read our [ranked proposal spots in Austin](/blog/best-places-to-propose-austin) — Lake Austin by boat is #1 for a reason." },
      { type: "h2", content: "Step 3: Ring, Speech, and Backup Plan" },
      { type: "ul", items: ["Keep the ring in a secure, dry pocket — not a cooler or open bag.", "Write bullet points, not a script; wind and emotion will change the delivery.", "Assign one person (friend or photographer) to capture video if you're not hiring a pro.", "Agree on a weather backup with your operator: reschedule window or a shorter scenic cruise."] },
      { type: "h2", content: "Step 4: What to Bring and Wear" },
      { type: "p", content: "Dress for photos and comfort: layers for after sunset, flat shoes for the dock, and nothing that can blow off the boat. Bring water, sunscreen, and a small celebration (champagne in cans or plastic flutes if allowed — no glass on most boats). If you're combining with dinner, book waterfront or downtown after — see [how to plan a marriage proposal in Austin](/blog/how-to-plan-marriage-proposal-austin) for the full timeline." },
      { type: "h2", content: "Ready to Plan Your Proposal?" },
      { type: "p", content: "Our private charters are built for moments like this. [Book your proposal cruise](/booking) — we'll help you make it perfect. Still exploring locations? Start with the [marriage proposal planning guide](/blog/how-to-plan-marriage-proposal-austin) or browse [Austin sunset cruise details](/blog/austin-sunset-cruise-guide) to see what the experience feels like before you commit." },
    ],
    relatedLinks: [PILLAR, BOOKING, SUNSET, AUSTIN_RENTAL, { href: "/blog/best-places-to-propose-austin", text: "Best places to propose in Austin", external: false }, { href: "/blog/how-to-plan-marriage-proposal-austin", text: "How to plan a marriage proposal in Austin", external: false }],
  },
  // #2 — Austin sunset cruise guide (full brief)
  {
    slug: "austin-sunset-cruise-guide",
    title: "The Perfect Austin Sunset Cruise: What to Expect, What to Bring & How to Book",
    excerpt:
      "Everything you need to know about a Lake Austin sunset cruise — what it's like, what to bring, best time to go, and how to book with Boat Bros ATX from $35/ticket.",
    date: "2026-05-18",
    author: "Boat Bros",
    image: "/photos/IMG_9647%202.webp",
    imageAlt: "Sunset cruise on Lake Austin with golden light over the water",
    category: "general",
    readingTimeMinutes: 10,
    seoKeywords: [
      "sunset cruise Austin",
      "Lake Austin sunset cruise",
      "romantic boat ride Austin",
      "Austin evening cruise",
      "Lake Austin sunset boat",
    ],
    keyTakeaways: [
      "Lake Austin sunset cruises run 2–3 hours and are best started 1–1.5 hours before official sunset for golden hour and twilight.",
      "Tickets from $35 make it one of the easiest romantic dates in Austin — same-day availability is often possible on weekdays.",
      "Bring sunscreen, a light layer, sunglasses, and a phone or camera; leave glass at home.",
      "A captained cruise means you enjoy the views — no driving, docking, or navigating in low light.",
      "Weekend and holiday sunset slots fill fast; book ahead or check same-day availability early in the day.",
    ],
    faqs: [
      { q: "How much does a sunset cruise on Lake Austin cost?", a: "Boat Bros sunset cruises on Lake Austin start from $35 per ticket depending on date and availability. Private charters cost more but give you the whole boat for your group." },
      { q: "What time should I arrive for an Austin sunset cruise?", a: "Arrive 15–20 minutes before departure. Your operator will confirm boarding time when you book — typically aligned so you're on the water 1–1.5 hours before sunset." },
      { q: "Is a Lake Austin sunset cruise romantic for couples?", a: "Yes. It's one of the most popular romantic things to do in Austin — calm water, Hill Country views, and golden light without the crowds of land-based sunset spots." },
      { q: "Can I book a sunset cruise the same day?", a: "Often yes on weekdays; weekends and peak season fill earlier. Check online or text the operator the morning of if you're planning last-minute." },
    ],
    body: [
      { type: "p", content: "**From $35/ticket — [book your sunset cruise tonight](/booking).** A Lake Austin sunset cruise is the easiest way to turn a regular evening into something you'll both remember: golden light on the water, Austin's hills in the background, and zero stress about parking or restaurant crowds. Whether it's a first big date or your tenth anniversary, here's what to expect, what to bring, and how to book. Pair this with our [50 best date ideas in Austin](/blog/50-best-date-ideas-austin) for more inspiration." },
      { type: "h2", content: "What a Lake Austin Sunset Cruise Feels Like" },
      { type: "p", content: "You'll board a comfortable pontoon or similar boat with your captain and group (or your private party if you booked a charter). After a quick safety briefing, you cruise toward scenic stretches — often toward [Tom Miller Dam](/blog/best-sunset-spots-austin-couples) or open water with the Pennybacker Bridge in frame. The engine quiets, the sun drops, and for twenty minutes the lake goes quiet in the best way. Most cruises run **2–3 hours** so you get golden hour and twilight, not just a quick lap." },
      { type: "h2", content: "Best Time to Go" },
      { type: "p", content: "Sunset times shift by season: spring and fall often land around 6:00–7:00 PM; summer can push past 8:00 PM. Plan to be **on the water 1–1.5 hours before official sunset**. Your captain picks departure so you're in position for the best light — that's the whole point of a [captained sunset experience](/experiences/sunset)." },
      { type: "h2", content: "What to Bring" },
      { type: "ul", items: ["Sunscreen — you're in the sun until the last light.", "Light jacket or layer — it gets breezy after dark.", "Sunglasses and phone/camera.", "Soft-sided cooler with drinks/snacks if allowed (no glass).", "Valid ID if your booking requires it."] },
      { type: "h2", content: "How to Book (and When to Book Early)" },
      { type: "p", content: "[Check sunset cruise availability](/booking) online or text us for same-day options. **Sunset slots fill fast on weekends** — especially spring through fall and around holidays. Weekdays are easier for spontaneous plans; see [date nights that don't need a reservation](/blog/austin-date-night-no-reservation) if you're deciding tonight." },
      { type: "h2", content: "Sunset Cruise vs. Private Charter" },
      { type: "p", content: "Ticketed sunset cruises are perfect for couples and small groups who want the vibe without renting the whole boat. Planning a [proposal on a boat](/blog/how-to-propose-on-a-boat-austin)? Book a private charter instead so you control the guest list and the moment. Either way, Lake Austin beats land-based overlooks for comfort and photos." },
      { type: "h2", content: "Don't Wait on Weekend Slots" },
      { type: "p", content: "Sunset on Lake Austin is the date Austin keeps recommending for a reason. [Book your sunset cruise](/booking) — we'll see you on the water. Explore [best sunset spots for couples](/blog/best-sunset-spots-austin-couples) if you want land options too, or read our [Austin boat rental guide](/austin-boat-rental) for private charter pricing." },
    ],
    relatedLinks: [PILLAR, BOOKING, SUNSET, { href: "/blog/how-to-propose-on-a-boat-austin", text: "How to propose on a boat in Austin", external: false }, { href: "/blog/best-sunset-spots-austin-couples", text: "Best sunset spots in Austin for couples", external: false }],
  },
  // #1 — Marriage proposal planning (full brief)
  {
    slug: "how-to-plan-marriage-proposal-austin",
    title: "How to Plan a Marriage Proposal in Austin That She'll Never Forget",
    excerpt:
      "Planning a proposal in Austin? From the perfect location to the exact moment — here's how to plan a marriage proposal in Austin that feels personal, romantic, and unforgettable.",
    date: "2026-05-17",
    author: "Boat Bros",
    image: "/photos/IMG_9647%202.webp",
    imageAlt: "Romantic Lake Austin setting for a marriage proposal",
    category: "general",
    readingTimeMinutes: 12,
    seoKeywords: ["proposal ideas Austin", "how to propose in Austin", "Austin engagement ideas", "romantic proposal spots Austin", "marriage proposal Austin TX"],
    keyTakeaways: [
      "Start with your partner's personality — introverts often prefer private Lake Austin moments; extroverts may love a story they'll retell with friends.",
      "Lake Austin boat proposals rank among the most successful in Austin: private, scenic, and captain-managed logistics.",
      "Build a simple timeline: one surprise activity (the proposal), one celebration meal, and no more than two location changes.",
      "Book vendors (boat, photographer, dinner) 2–4 weeks ahead for weekends; longer for holidays.",
      "Have a weather and backup plan — Austin spring storms move fast.",
    ],
    faqs: [
      { q: "Where is the best place to propose in Austin?", a: "Lake Austin by private boat is the top pick for privacy and scenery. Land options include Mount Bonnell, Zilker, and waterfront dining — see our ranked list of proposal spots." },
      { q: "When should I propose in Austin?", a: "Golden hour before sunset is ideal year-round. Avoid mid-day summer heat unless you're on the water with shade. Spring and fall offer the most comfortable temperatures." },
      { q: "Do I need a photographer for my Austin proposal?", a: "Not required, but highly recommended for boat proposals — your captain can help coordinate timing. A friend with a good phone works in a pinch." },
      { q: "How far in advance should I book a proposal experience?", a: "Book your boat or main experience 2–4 weeks ahead for weekends; 4–8 weeks for peak season and holidays." },
    ],
    body: [
      { type: "p", content: "Planning a marriage proposal in Austin should feel exciting, not like a second job. The city gives you everything: water, hills, great food, and experiences that photograph well without looking staged. This guide covers how to choose the moment, pick the location, and handle logistics so you can focus on the person in front of you. For dozens more ideas, start with [50 best date ideas in Austin](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "Know What \"Perfect\" Means for Your Partner" },
      { type: "p", content: "Some people want a public cheer; others want just the two of you and the lake. Ask yourself: Would they hate a crowd? Do they love photos? Are they anxious about surprises? Your answer points to **private boat** vs. **scenic overlook** vs. **dinner reveal**. There's no wrong answer — only wrong fit." },
      { type: "h2", content: "Choosing the Location" },
      { type: "p", content: "Our #1 recommendation for Austin proposals is a **[private Lake Austin charter](/booking)** — see [how to propose on a boat](/blog/how-to-propose-on-a-boat-austin) for the step-by-step. Water gives you privacy, backup weather options (stay on boat or reschedule), and a story that's uniquely Austin. Land lovers should read [15 best places to propose in Austin](/blog/best-places-to-propose-austin), ranked by romance and logistics." },
      { type: "p", content: "**Want the proposal handled for you?** Our private charters are built for this. [Book your proposal cruise](/booking) — we'll take care of the route and timing; you bring the ring and the words." },
      { type: "h2", content: "Build a Simple Day-Of Timeline" },
      { type: "ul", items: ["Morning or brunch — keep it normal so they don't suspect early.", "Afternoon buffer — don't rush; nerves need time.", "Proposal window — golden hour on the lake or your chosen spot.", "Celebration dinner — reserve waterfront or downtown; tell the restaurant it's a celebration.", "Optional: friends or family after, only if they'd love that energy."] },
      { type: "h2", content: "Ring, Photographer, and Discretion" },
      { type: "p", content: "Tell as few people as possible until after. If you hire a photographer, meet them beforehand at the dock. Combine with a [sunset cruise](/experiences/sunset) only if it's private — shared boats aren't proposal-friendly. After you're engaged, plan the engagement party with our [engagement party guide](/blog/engagement-party-austin)." },
      { type: "h2", content: "Book Your Proposal Cruise" },
      { type: "p", content: "[Book your proposal cruise](/booking) — we'll take care of the rest. Read [Austin proposal spots ranked](/blog/best-places-to-propose-austin) if you're still comparing locations, or [luxury date ideas](/blog/luxury-date-ideas-austin) if you want to extend the celebration into a full premium weekend." },
    ],
    relatedLinks: [PILLAR, BOOKING, SUNSET, { href: "/blog/how-to-propose-on-a-boat-austin", text: "How to propose on a boat", external: false }, { href: "/blog/best-places-to-propose-austin", text: "Best places to propose in Austin", external: false }],
  },
  // #3 — Anniversary ideas (full brief)
  {
    slug: "best-anniversary-ideas-austin",
    title: "Best Anniversary Ideas in Austin for Every Budget (From Free to Unforgettable)",
    excerpt:
      "Looking for anniversary ideas in Austin? From free outdoor experiences to luxury private charters on Lake Austin — here are the best ways to celebrate your anniversary in Austin.",
    date: "2026-05-16",
    author: "Boat Bros",
    image: "/photos/IMG_9647%202.webp",
    imageAlt: "Couple celebrating anniversary on Lake Austin at sunset",
    category: "general",
    readingTimeMinutes: 12,
    seoKeywords: ["anniversary ideas Austin", "Austin anniversary dinner", "romantic anniversary Austin", "anniversary activities Austin", "couples anniversary Austin TX"],
    keyTakeaways: [
      "Free tier: Mount Bonnell at sunset, Zilker picnic, or South Congress stroll — pair with a handwritten note.",
      "Mid tier: Sunset cruise from $35/ticket — big impact without private-charter pricing.",
      "Premium tier: Private Lake Austin charter — customize route, music, and timing for your anniversary.",
      "Combine water + dinner: boat first, then waterfront restaurants for a full arc.",
      "Book experiences before dinner reservations on busy weekends.",
    ],
    faqs: [
      { q: "What is a romantic anniversary idea in Austin on a budget?", a: "A Lake Austin sunset cruise starts from $35 per ticket — affordable luxury with captained logistics handled. Pair with a free sunset viewpoint before or after if you want to extend the evening." },
      { q: "What is the best luxury anniversary experience in Austin?", a: "A private captained charter on Lake Austin — customize timing for golden hour, bring champagne (no glass), and follow with waterfront or downtown dinner." },
      { q: "Should we do dinner or a boat for our anniversary?", a: "Do both if you can: boat for the emotional peak, dinner for the conversation. Book the boat first since sunset slots are limited." },
    ],
    body: [
      { type: "p", content: "Anniversaries deserve more than a reservation you made because OpenTable sent a reminder. Austin gives you free views, mid-range experiences that still feel special, and splurge-worthy options on the lake. Here's how to match your budget to something memorable — and tie it all back to our [50 best date ideas in Austin](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "Free & Low-Cost Anniversary Ideas" },
      { type: "p", content: "Mount Bonnell at golden hour, a Zilker picnic with your favorite takeout, or Barton Creek Greenbelt if you both hike. Cost is basically zero; effort is showing up with intention — a letter, photos from year one, or a playlist. Not every anniversary needs a invoice." },
      { type: "h2", content: "Mid-Budget: Sunset Cruise on Lake Austin" },
      { type: "p", content: "**Start with a [sunset cruise from $35](/booking).** You get captained logistics, lake views, and a clear \"we did something\" moment without private-charter pricing. It's the sweet spot for 1st, 5th, or \"we're saving for a trip\" years. See [what to expect on a sunset cruise](/blog/austin-sunset-cruise-guide)." },
      { type: "h2", content: "Premium: Private Charter Anniversary" },
      { type: "p", content: "Milestone years (10th, 25th) or \"we need a reset\" years call for a **[private Lake Austin charter](/experiences/lake-austin-pontoon)**. You pick the vibe — swim cove, sunset only, or slow cruise with music. More ideas in [luxury date ideas Austin](/blog/luxury-date-ideas-austin)." },
      { type: "h2", content: "Weekend-Long Celebrations" },
      { type: "p", content: "Turn it into a [2-day couples getaway](/blog/austin-weekend-getaway-couples-itinerary): boat day Saturday, brunch Sunday, hotel or staycation in East Austin or South Congress." },
      { type: "h2", content: "Your Anniversary Deserves More Than Dinner" },
      { type: "p", content: "[Book a Lake Austin experience](/booking) — sunset tickets or private charter. Your anniversary deserves the water, not just the table." },
    ],
    relatedLinks: [PILLAR, BOOKING, SUNSET, { href: "/blog/luxury-date-ideas-austin", text: "Luxury date ideas in Austin", external: false }, { href: "/blog/austin-weekend-getaway-couples-itinerary", text: "Austin weekend getaway for couples", external: false }],
  },
  // #4 — Surprise date (full brief)
  {
    slug: "how-to-plan-surprise-date-austin",
    title: "How to Plan a Surprise Date in Austin: A Step-by-Step Guide That Actually Works",
    excerpt:
      "Planning a surprise date in Austin? Here's a step-by-step guide to pulling it off — from choosing the experience to managing logistics without spoiling the moment.",
    date: "2026-05-15",
    author: "Boat Bros",
    image: "/photos/IMG_9647%202.webp",
    imageAlt: "Surprise romantic date on Lake Austin",
    category: "general",
    readingTimeMinutes: 9,
    seoKeywords: ["surprise date Austin", "surprise date ideas Austin", "how to plan a surprise date", "romantic surprise Austin", "secret date Austin"],
    keyTakeaways: [
      "Pick one surprise anchor (the boat) and keep everything else simple — over-planning increases leak risk.",
      "Use a cover story: \"dress casual, we're meeting friends\" or \"quick errand near the lake.\"",
      "Book captained experiences so you're not stressed driving or parking while managing the surprise.",
      "Sunset cruises are the easiest surprise — show up, board, done.",
      "Tell the operator it's a surprise; crew won't blow your cover.",
    ],
    faqs: [
      { q: "What is the easiest surprise date in Austin?", a: "A captained Lake Austin sunset cruise — you book, pick them up, and the experience runs itself. No reservations at multiple restaurants, no parking scavenger hunts." },
      { q: "How do I keep a surprise date secret?", a: "Book under your name, use a shared calendar block labeled vaguely, and tell only the boat operator. Avoid group texts and social posts until after." },
      { q: "What should they wear for a surprise boat date?", a: "Tell them casual and comfortable with layers — swimsuit optional under clothes if you might swim. Avoid heels on the dock." },
    ],
    body: [
      { type: "p", content: "Surprise dates fail for boring reasons: someone mentions the restaurant on Instagram, you're stuck in traffic, or you're so stressed about logistics you forget to be present. This step-by-step guide fixes that — built for Austin, where the lake is your best ally. More ideas in [50 best date ideas in Austin](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "Step 1: Choose One Anchor Experience" },
      { type: "p", content: "One big surprise beats three medium ones. **The easiest surprise date in Austin? A [sunset cruise](/experiences/sunset)** — we handle everything, you just show up. Mid-article truth: you don't need a scavenger hunt; you need a captained boat and a good cover story." },
      { type: "h2", content: "Step 2: Cover Story & Timing" },
      { type: "p", content: "Pick them up or meet at home with a vague plan: \"outfit for outdoors,\" \"we're running late, trust me.\" Arrive at the dock 15 minutes early; surprise happens at boarding or when the boat leaves the marina." },
      { type: "h2", content: "Step 3: Logistics Checklist" },
      { type: "ul", items: ["Book and pay ahead — no fumbling at the dock.", "Confirm parking or rideshare drop-off.", "Weather check morning-of; have dinner backup.", "Phone on silent; photos after the reveal."] },
      { type: "h2", content: "Step 4: Level Up for Milestones" },
      { type: "p", content: "Anniversary or makeup surprise? See [best anniversary ideas](/blog/best-anniversary-ideas-austin) or [luxury date ideas](/blog/luxury-date-ideas-austin) for private charter upgrades." },
      { type: "h2", content: "Book the Surprise They'll Talk About" },
      { type: "p", content: "[Book the surprise](/booking) — sunset cruise or private charter. They'll talk about it for years." },
    ],
    relatedLinks: [PILLAR, BOOKING, SUNSET, { href: "/blog/best-anniversary-ideas-austin", text: "Best anniversary ideas in Austin", external: false }],
  },
  // #5 — Proposal spots ranked (full brief)
  {
    slug: "best-places-to-propose-austin",
    title: "15 Best Places to Propose in Austin, TX (Ranked by Romance)",
    excerpt:
      "Where to propose in Austin? We ranked the 15 most romantic proposal spots in Austin — from Barton Springs to a private Lake Austin boat charter. Find the perfect moment.",
    date: "2026-05-14",
    author: "Boat Bros",
    image: "/photos/IMG_9647%202.webp",
    imageAlt: "Lake Austin — top ranked place to propose in Austin",
    category: "general",
    readingTimeMinutes: 14,
    seoKeywords: ["proposal spots Austin", "best places to propose Austin", "where to propose Austin TX", "Austin engagement locations", "romantic proposal Austin"],
    keyTakeaways: [
      "#1: Private Lake Austin boat proposal — privacy, views, captain-managed timing.",
      "Mount Bonnell is iconic but crowded at sunset — arrive early or go weekday.",
      "Zilker and Barton Springs work for active couples; plan for crowds and heat.",
      "Waterfront dinner proposals pair well with a boat earlier in the day.",
      "Always have a weather backup in Austin spring.",
    ],
    faqs: [
      { q: "What is the #1 place to propose in Austin?", a: "A private Lake Austin boat charter — ranked first for privacy, scenery, and controlled timing without tourist crowds." },
      { q: "Is Mount Bonnell good for proposals?", a: "Yes for views, but it's crowded at peak sunset. Weekday mornings or off-season evenings work better." },
      { q: "Can you propose on a public sunset cruise?", a: "Possible, but a private charter is better so the moment isn't shared with strangers. See our boat proposal guide." },
    ],
    body: [
      { type: "p", content: "Where to propose in Austin depends on whether your partner wants strangers cheering or just you and the skyline. We ranked 15 spots by romance, privacy, and logistics — with Lake Austin by boat at #1. Planning the full day? See [how to plan a marriage proposal in Austin](/blog/how-to-plan-marriage-proposal-austin) and [50 date ideas](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "#1 — Lake Austin Boat Proposal (Private Charter)" },
      { type: "p", content: "**Why it's #1:** Private water, Hill Country backdrop, no crowd behind you filming, captain handles boat so you're present. **[Book your private proposal charter](/booking)** — we'll help plan route and timing. Full playbook: [how to propose on a boat](/blog/how-to-propose-on-a-boat-austin)." },
      { type: "h2", content: "#2–5 — Water, Heights & Green Space" },
      { type: "ul", items: ["#2 Mount Bonnell — iconic sunset; go off-peak.", "#3 Zilker Park / Barton Springs area — active couples; morning better than sunset crowds.", "#4 Lady Bird Lake boardwalk — urban skyline; good for low-key.", "#5 Pennybacker Bridge overlook — stunning but windy and busy."] },
      { type: "h2", content: "#6–10 — Dining, Gardens & Hidden Corners" },
      { type: "ul", items: ["#6 Waterfront dinner (see our waterfront restaurant guide).", "#7 The Contemporary Austin Laguna Gloria — art + lake views.", "#8 Umlauf Sculpture Garden — quiet, artistic.", "#9 Mayfield Park — peacocks and ponds; morning magic.", "#10 Texas State Capitol grounds — if they love architecture and history."] },
      { type: "h2", content: "#11–15 — Day Trips, Rooftops & Seasonal" },
      { type: "ul", items: ["#11 Hamilton Pool (reserve early; weather dependent).", "#12 Rooftop bars downtown — sunset drinks then ring.", "#13 Hotel San José courtyard — intimate Austin vibe.", "#14 Wineries near Dripping Springs — full-day proposal trip.", "#15 [Sunset cruise ticket](/experiences/sunset) — mid-budget water option if private charter waits."] },
      { type: "h2", content: "Book Your #1 Spot" },
      { type: "p", content: "[Book your private proposal charter](/booking). Compare [marriage proposal planning](/blog/how-to-plan-marriage-proposal-austin) and [sunset cruise guide](/blog/austin-sunset-cruise-guide) next." },
    ],
    relatedLinks: [PILLAR, BOOKING, SUNSET, { href: "/blog/how-to-propose-on-a-boat-austin", text: "How to propose on a boat", external: false }, { href: "/blog/how-to-plan-marriage-proposal-austin", text: "Plan your marriage proposal", external: false }],
  },
  // #6
  {
    slug: "romantic-things-to-do-austin-weekend",
    title: "Romantic Things to Do in Austin This Weekend",
    excerpt: "Looking for romantic things to do in Austin this weekend? From Lake Austin sunset cruises to live music and waterfront dinners — here's what actually feels special.",
    date: "2026-05-13",
    author: "Boat Bros",
    image: "/photos/IMG_9647%202.webp",
    imageAlt: "Romantic weekend on Lake Austin",
    category: "general",
    readingTimeMinutes: 9,
    seoKeywords: ["romantic things to do in Austin", "Austin romantic activities", "couples things to do Austin", "Austin date night ideas", "weekend couples Austin"],
    keyTakeaways: ["Book your anchor experience first — sunset cruise or boat day — then build meals around it.", "Saturday lake + Saturday night dinner beats trying to cram six activities.", "Rain plan: museums, Hotel San José courtyard, or reschedule boat to Sunday.", "East Austin and South Congress are easy bases for lake access.", "Sunset cruise is the standout weekend experience most visitors miss."],
    faqs: [
      { q: "What is the most romantic thing to do in Austin this weekend?", a: "A Lake Austin sunset cruise — captained, scenic, and easy to book. It beats fighting crowds at overlooks." },
      { q: "Can we book a romantic Austin experience last minute?", a: "Weekday and off-peak sunset slots often have same-day availability. Weekends book earlier." },
    ],
    body: [
      { type: "p", content: "Weekend romance in Austin isn't about doing everything — it's about one experience that anchors the whole trip. For couples visiting or locals who never slow down, start with the lake. Full list: [50 best date ideas in Austin](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "Friday Night: Keep It Light" },
      { type: "p", content: "South Congress walk, live music on Rainey if you have energy, or early night if Saturday is the big day. Save the production value for tomorrow." },
      { type: "h2", content: "Saturday: Lake + Dinner" },
      { type: "p", content: "Morning coffee, then **[Lake Austin sunset cruise](/experiences/sunset)** or afternoon [pontoon](/experiences/lake-austin-pontoon) if you booked longer. This is the romantic thing to do in Austin that friends will ask about. Dinner: waterfront or downtown — see [waterfront restaurants](/blog/best-waterfront-restaurants-austin)." },
      { type: "h2", content: "Sunday: Brunch & Slow Down" },
      { type: "p", content: "Mattie's, Josephine House, or a patio in East Austin. Optional [picnic date](/blog/romantic-picnic-austin) if you want one more outdoor hit without spend." },
      { type: "p", content: "[Book this weekend's sunset cruise](/booking) before slots fill." },
    ],
    relatedLinks: [PILLAR, BOOKING, SUNSET, PONTOON, { href: "/blog/austin-weekend-getaway-couples-itinerary", text: "Weekend getaway itinerary", external: false }],
  },
  // #7
  {
    slug: "austin-bucket-list-couples",
    title: "Austin Bucket List for Couples: 25 Experiences You Have to Do Together",
    excerpt: "The ultimate Austin bucket list for couples — 25 experiences from Lake Austin boat days to live music, food, and hidden gems. How many have you done?",
    date: "2026-05-12",
    author: "Boat Bros",
    image: "/photos/IMG_1197.webp",
    imageAlt: "Couples bucket list experience on Lake Austin pontoon",
    category: "general",
    readingTimeMinutes: 11,
    seoKeywords: ["Austin bucket list couples", "couples bucket list Austin", "Austin experiences for couples", "things to do as a couple Austin", "Austin couples bucket list"],
    keyTakeaways: ["Lake Austin boat day is the #1 must-do — captained pontoon or sunset cruise.", "Mix water, music, food, and one Hill Country day trip for a complete list.", "Season matters: swim coves in summer, sunset cruises year-round.", "Many items are free; splurge on one lake experience.", "Use this list with the pillar date-ideas guide for planning."],
    faqs: [
      { q: "What should every couple do in Austin at least once?", a: "A day on Lake Austin — pontoon with captain or sunset cruise. It's the experience that defines Austin for couples." },
      { q: "How many items are on this Austin couples bucket list?", a: "25 — spanning lake, food, music, outdoors, and day trips." },
    ],
    body: [
      { type: "p", content: "An Austin bucket list for couples should feel achievable, not like homework. These 25 hits mix iconic and local — start with the lake. Companion guide: [50 best date ideas in Austin](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "On the Water (Do These First)" },
      { type: "ul", items: ["Lake Austin captained pontoon day", "Sunset cruise on Lake Austin", "Swim a quiet cove mid-lake", "Waterfront lunch at Ski Shores or Hula Hut from the boat", "Lady Bird Lake kayak at dusk"] },
      { type: "h2", content: "Food, Music & Culture" },
      { type: "ul", items: ["Live music on Sixth or Continental Club", "Tacos on a South Congress crawl", "Food trucks at Meanwhile Brewing", "Barton Springs polar plunge together", "Texas Capitol photo walk"] },
      { type: "h2", content: "Views, Trips & Seasonal" },
      { type: "ul", items: ["Mount Bonnell sunrise", "Hamilton Pool (reservations)", "Winery day in Hill Country", "Zilker holiday lights", "UT football game if you're fans", "East Austin mural walk", "BookPeople + coffee date", "Congress Bridge bats", "Blanton Museum afternoon", "Mayfield Park peacocks", "Domain outdoor dinner", "Trail of Lights", "Proposal or anniversary boat redo", "Group pontoon with friends", "Staycation lake day — see staycation guide"] },
      { type: "p", content: "Check off the boat: [Book Lake Austin](/booking) | [Austin boat rental guide](/austin-boat-rental)." },
    ],
    relatedLinks: [PILLAR, BOOKING, AUSTIN_RENTAL, PONTOON, SUNSET],
  },
  // #8
  {
    slug: "lake-austin-vs-lake-travis-romantic",
    title: "Lake Austin vs. Lake Travis: Which Is Better for a Romantic Day?",
    excerpt: "Lake Austin or Lake Travis for couples? Compare access, vibe, crowds, and romance — and why most Austin couples pick Lake Austin for date day.",
    date: "2026-05-11",
    author: "Boat Bros",
    image: "/photos/IMG_5116%202.webp",
    imageAlt: "Calm cove on Lake Austin for a romantic couples day",
    category: "lake-news",
    readingTimeMinutes: 8,
    seoKeywords: ["Lake Austin vs Lake Travis", "Lake Austin or Lake Travis for couples", "best lake Austin couples", "Lake Travis vs Lake Austin boat", "romantic lake Austin"],
    keyTakeaways: ["Lake Austin is 10–15 minutes from downtown; Lake Travis is 45+ minutes — romance dies in traffic.", "Lake Austin: constant water level, calmer coves, better for sunset cruises and proposals.", "Lake Travis: bigger party lake, The Oasis sunsets, more houseboat energy.", "For couples dates and proposals, Lake Austin wins almost every time.", "Boat Bros operates on Lake Austin — no long haul required."],
    faqs: [
      { q: "Which lake is better for a romantic date in Austin?", a: "Lake Austin — closer, calmer, and built for shorter premium experiences like sunset cruises and private charters." },
      { q: "Is Lake Travis worth it for couples?", a: "For big party groups or The Oasis visit, yes. For intimate romance and easy logistics, Lake Austin is better." },
    ],
    body: [
      { type: "p", content: "Couples Google \"Lake Austin vs Lake Travis\" because they don't want to waste a Saturday on the wrong water. Short answer: **for romance, Lake Austin.** Long answer below — plus [50 date ideas in Austin](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "Access & Logistics" },
      { type: "p", content: "Lake Austin hugs the city — you're on the water in minutes from downtown, East Austin, or South Congress. Lake Travis is a haul from most hotels; add traffic and you're tired before you board. Date energy matters." },
      { type: "h2", content: "Vibe: Intimate vs. Party" },
      { type: "p", content: "Lake Austin feels like a private escape with skyline and hills. Coves for swimming, [sunset cruises](/experiences/sunset), proposal charters. Lake Travis is larger, busier, famous for party boats and [The Oasis](https://oasis-austin.com/) crowds — fun for groups, less ideal for \"just us.\"" },
      { type: "h2", content: "Water Level & Predictability" },
      { type: "p", content: "Lake Austin is constant-level LCRA water — reliable shoreline year-round. Travis fluctuates; drought years change where you can beach." },
      { type: "h2", content: "Our Pick for Couples" },
      { type: "p", content: "Book [Lake Austin with Boat Bros](/austin-boat-rental). Still curious about cost? Read [is a boat rental worth it](/blog/is-boat-rental-austin-worth-it)." },
    ],
    relatedLinks: [PILLAR, AUSTIN_RENTAL, BOOKING, SUNSET, { href: "/blog/is-boat-rental-austin-worth-it", text: "Is a boat rental worth it?", external: false }],
  },
  // #9
  {
    slug: "outdoor-date-ideas-austin",
    title: "The Best Outdoor Date Ideas in Austin (That Aren't Just a Hike)",
    excerpt: "Outdoor date ideas in Austin beyond hiking — Lake Austin cruises, picnics, bats, paddleboards, and more for couples who want fresh air without a trail map.",
    date: "2026-05-10",
    author: "Boat Bros",
    image: "/photos/IMG_5116%202.webp",
    imageAlt: "Outdoor date on Lake Austin — not a hike",
    category: "general",
    readingTimeMinutes: 9,
    seoKeywords: ["outdoor date ideas Austin", "Austin outdoor activities couples", "outdoor romantic Austin", "nature date ideas Austin", "outside dates Austin"],
    keyTakeaways: ["Lake Austin boat cruise is the premium outdoor date — shade, water, no mileage.", "Pair picnic + sunset cruise for a full outdoor arc.", "Barton Springs and paddleboards are classic; add something new each season.", "Summer: morning or sunset only; avoid midday heat.", "Book outdoor anchors early on spring weekends."],
    faqs: [
      { q: "What is a romantic outdoor date in Austin besides hiking?", a: "A captained Lake Austin sunset cruise or pontoon afternoon — outdoor without exhaustion." },
    ],
    body: [
      { type: "p", content: "Not every couple wants to hike 8 miles in Texas heat. These outdoor date ideas in Austin keep you outside without making it a workout — anchored by the lake. More: [50 best date ideas](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "On the Water" },
      { type: "p", content: "[Sunset cruise](/experiences/sunset), [pontoon cove day](/experiences/lake-austin-pontoon), Lady Bird paddleboard at dusk. The boat is the outdoor date that still feels like a treat." },
      { type: "h2", content: "Picnics, Springs & Sky" },
      { type: "p", content: "Zilker picnic, [romantic picnic guide](/blog/romantic-picnic-austin), Barton Springs, Mount Bonnell, Congress Bridge bats, Umlauf Garden stroll." },
      { type: "h2", content: "Combine Picnic + Cruise" },
      { type: "p", content: "Pack lunch, then [book sunset](/booking) — best of both. See [outdoor + waterfront dinner](/blog/best-waterfront-restaurants-austin)." },
    ],
    relatedLinks: [PILLAR, SUNSET, BOOKING, { href: "/blog/romantic-picnic-austin", text: "Romantic picnic in Austin", external: false }, { href: "/blog/austin-sunset-cruise-guide", text: "Austin sunset cruise guide", external: false }],
  },
  // #10 — Weekend getaway (full brief)
  {
    slug: "austin-weekend-getaway-couples-itinerary",
    title: "The Perfect Austin Weekend Getaway for Couples: A 2-Day Itinerary Built Around the Lake",
    excerpt: "Planning a couples weekend in Austin? Here's a 2-day itinerary built around the best Austin has to offer — including a Lake Austin boat day as the centerpiece experience.",
    date: "2026-05-09",
    author: "Boat Bros",
    image: "/photos/IMG_1197.webp",
    imageAlt: "Couples weekend getaway on Lake Austin",
    category: "general",
    readingTimeMinutes: 11,
    seoKeywords: ["Austin weekend getaway couples", "couples weekend Austin", "Austin romantic weekend", "Austin 2-day itinerary couples", "weekend trip Austin couples"],
    keyTakeaways: ["Day 1 centers on Lake Austin — book boat experience before restaurants.", "Stay East Austin, Downtown, or South Congress for lake + nightlife access.", "Day 2: brunch, South Congress, optional springs or museum.", "Don't over-schedule; the boat day is the memory.", "Book Boat Bros early for summer weekends."],
    faqs: [
      { q: "What is the best 2-day couples itinerary in Austin?", a: "Day 1: brunch, Lake Austin boat afternoon/sunset, dinner. Day 2: brunch, South Congress, depart or optional springs." },
    ],
    body: [
      { type: "p", content: "The best Austin weekend getaway for couples has one rule: **build around the lake.** Everything else — dinner, music, hotel — supports the boat day. Itinerary below; ideas bank: [50 best date ideas in Austin](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "Day 1 — Lake as Centerpiece" },
      { type: "ul", items: ["Late brunch: Aba, Launderette, or Veracruz on the way to the water.", "Early afternoon: [Book your Lake Austin boat day](/booking) — pontoon or sunset.", "Late afternoon: shower, rest at hotel/Airbnb.", "Dinner: waterfront or downtown — [waterfront picks](/blog/best-waterfront-restaurants-austin).", "Optional: Rainey or low-key wine bar — pace yourselves."] },
      { type: "p", content: "**Book your Lake Austin boat day — the rest of the weekend falls into place.**" },
      { type: "h2", content: "Day 2 — Austin Flavor" },
      { type: "ul", items: ["Brunch: Mattie's or Josephine House.", "South Congress: shops, coffee, photos.", "Optional: Barton Springs or Blanton if weather cooperates.", "Depart or extend with [staycation ideas](/blog/austin-staycation-couples)."] },
      { type: "h2", content: "Where to Stay" },
      { type: "p", content: "East Austin Airbnbs, downtown hotels, or South Congress — all 10–15 minutes to Lake Austin marinas. See [anniversary ideas](/blog/best-anniversary-ideas-austin) for splurge upgrades." },
      { type: "p", content: "[Book your weekend boat experience](/booking) | [Pontoon details](/experiences/lake-austin-pontoon)." },
    ],
    relatedLinks: [PILLAR, BOOKING, SUNSET, { href: "/blog/best-waterfront-restaurants-austin", text: "Waterfront restaurants", external: false }, { href: "/blog/best-anniversary-ideas-austin", text: "Anniversary ideas", external: false }],
  },
  // #11
  {
    slug: "unique-date-ideas-austin",
    title: "Unique Date Ideas in Austin That Most Couples Haven't Tried",
    excerpt: "Unusual and creative date ideas in Austin — off the beaten path experiences including Lake Austin boat cruises most locals still haven't done.",
    date: "2026-05-08",
    author: "Boat Bros",
    image: "/photos/IMG_9647%202.webp",
    imageAlt: "Unique date on Lake Austin",
    category: "general",
    readingTimeMinutes: 8,
    seoKeywords: ["unique date ideas Austin", "unusual date ideas Austin", "creative date ideas Austin", "Austin date ideas off the beaten path", "different dates Austin"],
    keyTakeaways: ["Private sunset charter beats another rooftop bar.", "Try a weekday lake day — coves nearly empty.", "Combine unexpected: picnic + boat + vinyl shop crawl.", "Umlauf, Mayfield, and Laguna Gloria are underused.", "Boat cruise is unique because most couples only dine out."],
    faqs: [{ q: "What is a unique date in Austin?", a: "Weekday captained pontoon in a quiet cove, or a private sunset charter — most couples haven't done it even if they live here." }],
    body: [
      { type: "p", content: "Unique date ideas in Austin aren't secret speakeasies only — they're experiences locals skip because they feel \"touristy\" until they go. The lake is the biggest one. Full list: [50 date ideas](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "Most Unique: Lake Austin Your Way" },
      { type: "p", content: "Weekday [pontoon](/experiences/lake-austin-pontoon), themed playlist, swim cove — not a bar crawl. Or [propose-level private charter](/blog/how-to-propose-on-a-boat-austin) for a big anniversary without the ring." },
      { type: "h2", content: "More Offbeat Austin Dates" },
      { type: "ul", items: ["Mayfield Park morning + coffee", "Laguna Gloria + sculpture walk", "Meanwhile Brewing + food trucks", "Vinyl crawl on North Loop", "Midnight kayak (guided tours seasonally)", "Cooking class + stay in", "Drive-in Volente or classic Paramount screening"] },
      { type: "p", content: "[Book the date they'll remember](/booking)." },
    ],
    relatedLinks: [PILLAR, BOOKING, PONTOON, { href: "/blog/austin-experiences-worth-the-hype", text: "Experiences worth the hype", external: false }],
  },
  // #12
  {
    slug: "austin-staycation-couples",
    title: "How to Plan the Perfect Austin Staycation for Two",
    excerpt: "Romantic Austin staycation ideas for couples — treat your city like a getaway with a Lake Austin boat day as the anchor activity.",
    date: "2026-05-07",
    author: "Boat Bros",
    image: "/photos/IMG_1197.webp",
    imageAlt: "Austin staycation couples on pontoon",
    category: "general",
    readingTimeMinutes: 8,
    seoKeywords: ["Austin staycation couples", "Austin staycation ideas", "romantic staycation Austin", "Austin couples staycation", "local getaway Austin"],
    keyTakeaways: ["Book a hotel or Airbnb in a new neighborhood — East Austin or South Congress.", "One splurge activity: Lake Austin boat day.", "Unplug: phones away on the water.", "Eat somewhere you've never been after the boat.", "Staycation works any season with sunset cruises."],
    faqs: [{ q: "What is a good Austin staycation for couples?", a: "One night away in a new neighborhood plus a captained Lake Austin day — boat as anchor, dinner as celebration." }],
    body: [
      { type: "p", content: "You don't need a flight to feel away. An Austin staycation for couples = new bed + one unforgettable day. Make that day the lake. Ideas: [50 best date ideas](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "Staycation Formula" },
      { type: "ul", items: ["Check into hotel/Airbnb Friday or Saturday.", "Saturday: [Lake Austin pontoon or sunset](/booking).", "Saturday dinner: splurge tier from [worth it experiences](/blog/austin-experiences-worth-splurging-couples).", "Sunday brunch + slow morning."] },
      { type: "p", content: "Locals: see [weekend itinerary](/blog/austin-weekend-getaway-couples-itinerary) for full schedule." },
    ],
    relatedLinks: [PILLAR, BOOKING, PONTOON, { href: "/blog/austin-weekend-getaway-couples-itinerary", text: "Weekend itinerary", external: false }],
  },
  // #13 — Luxury (full brief)
  {
    slug: "luxury-date-ideas-austin",
    title: "Luxury Date Ideas in Austin: Premium Experiences Worth Every Penny",
    excerpt: "Luxury date ideas in Austin — private boat charters, rooftop dining, spa days, and premium couples experiences that deliver on the price tag.",
    date: "2026-05-06",
    author: "Boat Bros",
    image: "/photos/IMG_1197.webp",
    imageAlt: "Luxury private charter on Lake Austin",
    category: "general",
    readingTimeMinutes: 10,
    seoKeywords: ["luxury date ideas Austin", "upscale date ideas Austin", "high-end Austin experiences couples", "Austin luxury experiences", "premium dates Austin"],
    keyTakeaways: ["#1 luxury date: private Lake Austin charter — you control timing, music, guest list.", "Pair charter with chef's table or waterfront fine dining.", "Spa half-day + sunset boat is a full premium arc.", "Book private experiences 3–4 weeks ahead in peak season.", "Luxury is logistics-free — captained boat delivers that."],
    faqs: [
      { q: "What is the best luxury date in Austin?", a: "A private captained Lake Austin charter at golden hour, followed by upscale dinner — customizable and private." },
    ],
    body: [
      { type: "p", content: "Luxury date ideas in Austin should feel effortless, not like you coordinated six vendors. Here's what earns the price — starting with the water. More: [50 best date ideas](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "#1 — Private Lake Austin Charter" },
      { type: "p", content: "Your boat, your captain, your playlist. Swim cove, sunset, proposal setup — whatever the milestone needs. **[Book a private charter](/booking)** and we'll customize. Compare [anniversary tiers](/blog/best-anniversary-ideas-austin)." },
      { type: "h2", content: "More Premium Austin Dates" },
      { type: "ul", items: ["Chef's table: Odd Duck, Barley Swine tasting", "Spa morning at Lake Austin Spa Resort + afternoon boat", "Helicopter tour + dinner downtown (splurge combo)", "Wine country car service day", "Suite at Commodore Perry + sunset cruise"] },
      { type: "h2", content: "Private Charters" },
      { type: "p", content: "Private charters start at varying rates by date and duration — [book yours](/booking) and we'll customize the experience. See [splurge-worthy experiences](/blog/austin-experiences-worth-splurging-couples)." },
    ],
    relatedLinks: [PILLAR, BOOKING, PONTOON, { href: "/blog/best-anniversary-ideas-austin", text: "Anniversary ideas", external: false }, { href: "/blog/austin-weekend-getaway-couples-itinerary", text: "Weekend getaway", external: false }],
  },
  // #14
  {
    slug: "valentines-day-austin-ideas",
    title: "What to Do on Valentine's Day in Austin (Beyond Dinner Reservations)",
    excerpt: "Valentine's Day in Austin beyond crowded restaurants — sunset cruises, private charters, and romantic experiences that book before the steakhouses fill up.",
    date: "2026-05-05",
    author: "Boat Bros",
    image: "/photos/IMG_9647%202.webp",
    imageAlt: "Valentine's Day sunset cruise Lake Austin",
    category: "general",
    readingTimeMinutes: 8,
    seoKeywords: ["Valentine's Day Austin", "Austin Valentine's Day ideas", "Valentine's Day date Austin", "romantic Valentine's Austin", "Valentine's Austin couples"],
    keyTakeaways: ["Book boat experiences before restaurant reservations — fewer slots.", "Valentine's sunset cruise = built-in romance without menu prix fixe stress.", "Private charter if you want zero crowds.", "Week-before flower delivery; day-of is boat + dinner.", "Galentine's and friend groups: pontoon charter works too."],
    faqs: [
      { q: "What should couples do on Valentine's Day in Austin?", a: "Lake Austin sunset cruise or private charter, then a reservation-light dinner or waterfront meal." },
    ],
    body: [
      { type: "p", content: "Valentine's Day in Austin doesn't have to mean a $200 prefix menu and a crowded dining room. Put the emotion on the water. See also [50 date ideas](/blog/50-best-date-ideas-austin) and [anniversary ideas](/blog/best-anniversary-ideas-austin)." },
      { type: "h2", content: "Valentine's on the Lake" },
      { type: "p", content: "[Sunset cruise](/experiences/sunset) for classic romance; [private charter](/booking) for proposals or milestone V-Days. Book early — Valentine's weekend sells out." },
      { type: "h2", content: "Beyond Dinner" },
      { type: "ul", items: ["Morning flowers + evening boat", "Couples massage + sunset", "Cook at home, boat next weekend if V-Day is sold out", "Stargazing at Mount Bonnell after cruise"] },
      { type: "p", content: "[Book Valentine's sunset](/booking)." },
    ],
    relatedLinks: [PILLAR, BOOKING, SUNSET, { href: "/blog/best-anniversary-ideas-austin", text: "Anniversary ideas", external: false }, { href: "/blog/luxury-date-ideas-austin", text: "Luxury date ideas", external: false }],
  },
  // #15
  {
    slug: "austin-date-night-no-reservation",
    title: "Austin Date Night Ideas That Don't Require a Reservation",
    excerpt: "Last-minute and spontaneous Austin date nights — sunset cruises with same-day tickets, food trucks, overlooks, and more without a Resy hunt.",
    date: "2026-05-04",
    author: "Boat Bros",
    image: "/photos/IMG_9647%202.webp",
    imageAlt: "Spontaneous sunset date Lake Austin",
    category: "general",
    readingTimeMinutes: 7,
    seoKeywords: ["Austin date night no reservation", "last-minute date ideas Austin", "spontaneous date Austin", "Austin date night ideas", "same day date Austin"],
    keyTakeaways: ["Sunset cruises often have same-day availability weekdays.", "Food truck parks need no reservation.", "Mount Bonnell and boardwalk walks are free and instant.", "Text operators morning-of for boat availability.", "Surprise dates work best with one booked anchor."],
    faqs: [{ q: "What can we do in Austin tonight without a reservation?", a: "Check same-day sunset cruise availability, hit Meanwhile or food truck parks, or Mount Bonnell at sunset." }],
    body: [
      { type: "p", content: "No reservation? No problem. Austin rewards spontaneity if you pick the right anchor. Best last-minute win: the lake. [50 date ideas](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "Same-Day Wins" },
      { type: "ul", items: ["[Sunset cruise tickets](/booking) — check online or text us", "Food trucks: Meanwhile, Thicket", "Lady Bird Lake walk + ice cream", "Live music venues with door-only entry", "South Congress window shopping + tacos"] },
      { type: "p", content: "Planning a surprise? [Surprise date guide](/blog/how-to-plan-surprise-date-austin)." },
    ],
    relatedLinks: [PILLAR, BOOKING, SUNSET, { href: "/blog/how-to-plan-surprise-date-austin", text: "Plan a surprise date", external: false }],
  },
  // #16
  {
    slug: "engagement-party-austin",
    title: "How to Plan an Engagement Party in Austin",
    excerpt: "Engagement party ideas in Austin — venues, lake charters, guest lists, and how to celebrate without duplicating the wedding.",
    date: "2026-05-03",
    author: "Boat Bros",
    image: "/photos/IMG_1197.webp",
    imageAlt: "Engagement party on Lake Austin pontoon",
    category: "general",
    readingTimeMinutes: 9,
    seoKeywords: ["engagement party Austin", "Austin engagement party ideas", "engagement celebration Austin", "where to have engagement party Austin", "engagement party venue Austin"],
    keyTakeaways: ["Lake Austin pontoon charter fits 10–14 guests — ideal engagement party venue.", "Book 4–6 weeks ahead for weekend charters.", "Keep it distinct from wedding: casual dress, shorter timeline.", "Coordinate catering or BYO food rules with operator.", "Combine proposal story + boat for emotional toast moment."],
    faqs: [
      { q: "Where should I host an engagement party in Austin?", a: "A captained Lake Austin pontoon for medium groups, or private charter for intimate celebrations — memorable and photogenic." },
    ],
    body: [
      { type: "p", content: "After the proposal — on a [boat](/blog/how-to-propose-on-a-boat-austin) or land — celebrate with people who matter. Austin engagement parties shine on the water. [50 date ideas](/blog/50-best-date-ideas-austin) for couple time before the big guest list." },
      { type: "h2", content: "Why a Boat Engagement Party Works" },
      { type: "p", content: "Private [pontoon charter](/experiences/lake-austin-pontoon): captain drives, you host, skyline behind toasts. No venue rental minimums, built-in activity." },
      { type: "h2", content: "Planning Checklist" },
      { type: "ul", items: ["Guest count & charter size", "BYO food/drink rules (no glass)", "Music playlist + phone speaker", "Photo time at golden hour", "Rain backup date with operator"] },
      { type: "p", content: "[Book engagement party charter](/booking) | [Proposal planning](/blog/how-to-plan-marriage-proposal-austin)." },
    ],
    relatedLinks: [PILLAR, BOOKING, PONTOON, { href: "/blog/how-to-propose-on-a-boat-austin", text: "Boat proposal guide", external: false }, { href: "/blog/best-places-to-propose-austin", text: "Proposal spots", external: false }],
  },
  // #17
  {
    slug: "best-waterfront-restaurants-austin",
    title: "Best Waterfront Restaurants in Austin for a Romantic Dinner",
    excerpt: "Romantic waterfront and lakeside dining in Austin — Ski Shores, Hula Hut, County Line, and how to pair dinner with a Lake Austin boat day.",
    date: "2026-05-02",
    author: "Boat Bros",
    image: "/photos/IMG_5116%202.webp",
    imageAlt: "Waterfront dining on Lake Austin",
    category: "general",
    readingTimeMinutes: 9,
    seoKeywords: ["waterfront restaurants Austin", "Austin lakeside dining", "romantic waterfront dining Austin", "Lake Austin restaurants", "lakeside date Austin"],
    keyTakeaways: ["Ski Shores, Hula Hut, County Line are on Lake Austin with dock access.", "The Oasis is on Lake Travis — longer drive from downtown lake days.", "Best romantic move: boat afternoon + waterfront dinner same day.", "Reserve for groups; walk-in possible weekdays at some spots.", "Boat Bros captains can coordinate lake restaurant stops."],
    faqs: [
      { q: "What is the most romantic waterfront restaurant in Austin?", a: "County Line on the Lake for scenery; Ski Shores for classic lake vibe; pair any with a sunset boat earlier." },
    ],
    body: [
      { type: "p", content: "Waterfront restaurants in Austin hit different when you've already been on the water. Here's where to eat — and how to do **both** boat and dinner. Lake dining detail: [restaurants on a boat day](/blog/best-restaurants-lake-austin-boat-day). Date ideas: [50 best](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "Lake Austin (On the Water)" },
      { type: "ul", items: ["Ski Shores Cafe — burgers, tacos, dock culture", "Hula Hut — Tex-Mex, margaritas, lively", "County Line on the Lake — barbecue, quiet deck"] },
      { type: "h2", content: "Do Both: Cruise + Dinner" },
      { type: "p", content: "Morning or afternoon [pontoon](/experiences/lake-austin-pontoon), dock for dinner, or [sunset cruise](/experiences/sunset) then drive to downtown. **[Book your boat day](/booking)** — we'll help time restaurant stops." },
      { type: "h2", content: "Lake Travis Note" },
      { type: "p", content: "The Oasis is famous but on Travis — see [Lake Austin vs Travis](/blog/lake-austin-vs-lake-travis-romantic) for couples logistics." },
    ],
    relatedLinks: [PILLAR, BOOKING, PONTOON, { href: "/blog/austin-weekend-getaway-couples-itinerary", text: "Weekend itinerary", external: false }, { href: "/blog/best-restaurants-lake-austin-boat-day", text: "Restaurants on a boat day", external: false }],
  },
  // #18
  {
    slug: "austin-couples-activities",
    title: "Austin Couples Activities: 20 Things to Do Together in Austin",
    excerpt: "20 Austin couples activities — from Lake Austin boats to music, food, and outdoors. The standout experience most pairs should book first.",
    date: "2026-05-01",
    author: "Boat Bros",
    image: "/photos/IMG_1197.webp",
    imageAlt: "Couples activities on Lake Austin",
    category: "general",
    readingTimeMinutes: 9,
    seoKeywords: ["couples activities Austin", "things to do as a couple Austin", "Austin activities for two", "Austin couples experiences", "date activities Austin"],
    keyTakeaways: ["Lake Austin boat cruise is the standout — book it first.", "Mix 3 categories: water, culture, food.", "Seasonal: bats in summer, lights in winter.", "Many activities pair with [bucket list](/blog/austin-bucket-list-couples).", "Groups: see group date guide for pontoon."],
    faqs: [{ q: "What is the best activity for couples in Austin?", a: "A captained Lake Austin experience — sunset cruise or pontoon — for scenery, ease, and memorability." }],
    body: [
      { type: "p", content: "Twenty Austin couples activities — no fluff. Start with #1 on the water. Full library: [50 date ideas](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "20 Activities" },
      { type: "ul", items: ["Lake Austin sunset cruise", "Captained pontoon cove day", "Barton Springs swim", "Live music on Sixth", "South Congress afternoon", "Mount Bonnell sunset", "Food truck date", "Laguna Gloria museum", "Paddleboard Lady Bird", "Cooking class together", "Winery day trip", "Zilker picnic", "Bat watching Congress Bridge", "Bike the trail", "Bookstore date + coffee", "Thai Kun or upscale tasting menu", "Group pontoon with friends", "Staycation hotel night", "Anniversary boat redo", "Proposal charter when ready"] },
      { type: "p", content: "[Book couples activity on the lake](/booking)." },
    ],
    relatedLinks: [PILLAR, BOOKING, SUNSET, PONTOON, { href: "/blog/romantic-things-to-do-austin-weekend", text: "Romantic weekend ideas", external: false }],
  },
  // #19
  {
    slug: "romantic-picnic-austin",
    title: "How to Plan a Romantic Picnic in Austin (And What to Do After)",
    excerpt: "Romantic picnic spots in Austin plus what to do after — sunset cruise, waterfront dinner, and easy upgrades from a blanket date.",
    date: "2026-04-30",
    author: "Boat Bros",
    image: "/photos/IMG_5116%202.webp",
    imageAlt: "Romantic picnic in Austin leading to lake sunset",
    category: "general",
    readingTimeMinutes: 8,
    seoKeywords: ["romantic picnic Austin", "Austin picnic spots couples", "picnic date Austin", "outdoor romantic Austin", "picnic date ideas Austin"],
    keyTakeaways: ["Zilker, Pease Park, and Laguna Gloria lawns work well.", "Pack no-glass drinks, blanket, bug spray.", "Best arc: picnic late afternoon → sunset cruise after.", "Summer: shade and sunset timing only.", "After picnic, boat beats sitting in traffic to a restaurant."],
    faqs: [{ q: "What should we do after a picnic date in Austin?", a: "Book a Lake Austin sunset cruise — easy upgrade from picnic without planning a second venue." }],
    body: [
      { type: "p", content: "A romantic picnic in Austin is affordable and personal — but the best versions have a **chapter two**. Here's how to plan the picnic and what to do after. [50 date ideas](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "Picnic Spots" },
      { type: "ul", items: ["Zilker great lawn (busy weekends)", "Pease Park shade", "Laguna Gloria views", "Mount Bonnell if you'll leave before crowds", "McKinney Falls for nature drive"] },
      { type: "h2", content: "What to Pack" },
      { type: "p", content: "Charcuterie, sandwiches, canned wine or sparkling water, blanket, trash bag, sunscreen." },
      { type: "h2", content: "After the Picnic" },
      { type: "p", content: "**CTA: [Sunset cruise](/experiences/sunset)** — you already ate; now get the skyline. [Book after your picnic](/booking). See [outdoor dates](/blog/outdoor-date-ideas-austin)." },
    ],
    relatedLinks: [PILLAR, BOOKING, SUNSET, { href: "/blog/outdoor-date-ideas-austin", text: "Outdoor date ideas", external: false }],
  },
  // #20
  {
    slug: "austin-experiences-worth-splurging-couples",
    title: "Austin Experiences Worth Splurging On (For Couples)",
    excerpt: "Couples splurge experiences in Austin that deliver — private Lake Austin charters, chef's tables, spa days, and what to skip.",
    date: "2026-04-29",
    author: "Boat Bros",
    image: "/photos/IMG_1197.webp",
    imageAlt: "Splurge-worthy Lake Austin couples experience",
    category: "general",
    readingTimeMinutes: 8,
    seoKeywords: ["Austin experiences worth it", "best Austin experiences couples", "Austin splurge experiences", "premium Austin activities", "worth it Austin couples"],
    keyTakeaways: ["Private Lake Austin charter = highest emotional ROI for couples.", "Chef's tables and spa+boat combos justify price.", "Skip overhyped lines if experience doesn't match — see hype guide.", "Splurge on logistics-free (captained) over DIY stress.", "One splurge beats three mediocre outings."],
    faqs: [{ q: "What Austin experience is worth the money for couples?", a: "A private captained Lake Austin charter — customizable, private, and consistently rated as the memory couples keep." }],
    body: [
      { type: "p", content: "Splurge means **value**, not just price. These Austin experiences earn it — led by the lake. [Luxury dates](/blog/luxury-date-ideas-austin) | [50 ideas](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "Worth It" },
      { type: "ul", items: ["Private Lake Austin charter", "Lake Austin Spa + sunset boat", "Tasting menu at Odd Duck / Barley Swine", "Small-group wine tour with driver", "Sunset cruise when private isn't in budget"] },
      { type: "h2", content: "Skip or Downgrade" },
      { type: "p", content: "Overpriced tourist traps with long lines — see [worth the hype](/blog/austin-experiences-worth-the-hype). DIY boat rental if no one wants to captain." },
      { type: "p", content: "[Book the splurge that delivers](/booking)." },
    ],
    relatedLinks: [PILLAR, BOOKING, PONTOON, { href: "/blog/luxury-date-ideas-austin", text: "Luxury date ideas", external: false }, { href: "/blog/is-boat-rental-austin-worth-it", text: "Is boat rental worth it?", external: false }],
  },
  // #22
  {
    slug: "best-sunset-spots-austin-couples",
    title: "Best Sunset Spots in Austin for Couples",
    excerpt: "Where to watch the sunset in Austin — ranked overlooks, waterfront spots, and why a Lake Austin sunset cruise is #1 for couples.",
    date: "2026-04-28",
    author: "Boat Bros",
    image: "/photos/IMG_9647%202.webp",
    imageAlt: "Best sunset spot Lake Austin for couples",
    category: "general",
    readingTimeMinutes: 9,
    seoKeywords: ["sunset spots Austin", "best sunsets Austin", "where to watch sunset Austin", "Austin sunset views", "romantic sunset Austin"],
    keyTakeaways: ["#1: Lake Austin sunset cruise — moving viewpoint, no crowd at your shoulder.", "Mount Bonnell and Bridge overlook are classic but crowded.", "Laguna Gloria and waterfront decks combine art + sun.", "Arrive 45–60 min before official sunset.", "Pair land sunset with boat another night for best photos."],
    faqs: [{ q: "Where is the best sunset in Austin for couples?", a: "On Lake Austin via sunset cruise — unobstructed water views and captained timing for golden hour." }],
    body: [
      { type: "p", content: "Best sunset spots in Austin for couples — ranked. Spoiler: the water wins. Details: [sunset cruise guide](/blog/austin-sunset-cruise-guide) | [50 date ideas](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "#1 — Lake Austin Sunset Cruise" },
      { type: "p", content: "You're **in** the sunset, not fighting for parking. [Book sunset cruise](/booking) from $35/ticket." },
      { type: "h2", content: "Land Spots (#2–8)" },
      { type: "ul", items: ["Mount Bonnell", "Pennybacker Bridge overlook", "Laguna Gloria", "Lady Bird boardwalk", "The Oasis (Lake Travis — farther)", "Hotel rooftop bars", "Zilker open field", "Congress Avenue bridge angle"] },
      { type: "p", content: "Ready to upgrade from the overlook? [Sunset cruise](/experiences/sunset)." },
    ],
    relatedLinks: [PILLAR, BOOKING, SUNSET, { href: "/blog/austin-sunset-cruise-guide", text: "Sunset cruise guide", external: false }],
  },
  // #23
  {
    slug: "date-ideas-new-couples-austin",
    title: "Austin Date Ideas for New Couples (First 3 Months)",
    excerpt: "Early relationship date ideas in Austin — low pressure, high connection, including the sunset cruise that accelerates the 'wow' moment.",
    date: "2026-04-27",
    author: "Boat Bros",
    image: "/photos/IMG_9647%202.webp",
    imageAlt: "New couple date on Lake Austin sunset cruise",
    category: "general",
    readingTimeMinutes: 7,
    seoKeywords: ["date ideas new couples Austin", "first date ideas Austin", "early relationship date ideas Austin", "Austin dates for new couples", "new relationship Austin"],
    keyTakeaways: ["Start low-pressure: coffee, walk, food trucks.", "Save big splash for date 3–5: sunset cruise.", "Avoid over-planning multi-stop marathons early.", "Ask what they hate (hiking, crowds) before booking boat.", "Sunset cruise is impressive but not too intense for new couples."],
    faqs: [{ q: "What is a good third date in Austin?", a: "A Lake Austin sunset cruise — memorable, 2–3 hours, conversation-friendly, not as intense as a full-day pontoon." }],
    body: [
      { type: "p", content: "New couples in Austin don't need to prove anything with a $400 dinner. Build connection, then add wow. [50 date ideas](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "Dates 1–3" },
      { type: "ul", items: ["Coffee + walk South Congress", "Food trucks at Meanwhile", "Museum or bookstore afternoon"] },
      { type: "h2", content: "Dates 4+ — Add Wow" },
      { type: "p", content: "[Sunset cruise](/experiences/sunset) — accelerates connection without all-day commitment. Later: [unique ideas](/blog/unique-date-ideas-austin)." },
      { type: "p", content: "[Book sunset](/booking)." },
    ],
    relatedLinks: [PILLAR, BOOKING, SUNSET, { href: "/blog/unique-date-ideas-austin", text: "Unique date ideas", external: false }],
  },
  // #24 — LDR (high conversion)
  {
    slug: "long-distance-relationship-austin-visit",
    title: "Long-Distance Relationship Visit to Austin: How to Make It Unforgettable",
    excerpt: "Visiting your partner in Austin? LDR date ideas that maximize limited time together — Lake Austin boat day as the can't-miss experience.",
    date: "2026-04-26",
    author: "Boat Bros",
    image: "/photos/IMG_1197.webp",
    imageAlt: "Long distance couple reunion on Lake Austin",
    category: "general",
    readingTimeMinutes: 9,
    seoKeywords: ["long distance relationship Austin visit", "LDR Austin date ideas", "visiting partner Austin", "Austin romantic visit", "long distance Austin couples"],
    keyTakeaways: ["One anchor experience per visit — don't overschedule.", "Lake Austin boat day = maximum memory per hour.", "Book boat before restaurants when time is short.", "Take photos and unplug on the water.", "Locals: let them show neighborhood; visitor: bring one surprise booking."],
    faqs: [
      { q: "What should long-distance couples do in Austin?", a: "Book a captained Lake Austin experience — sunset cruise or pontoon — for a focused, memorable block of quality time." },
    ],
    body: [
      { type: "p", content: "Long-distance relationship visits to Austin are scarce — make hours count. One perfect afternoon on the lake beats six mediocre stops. [50 date ideas](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "The \"Make It Count\" Experience" },
      { type: "p", content: "**[Lake Austin boat day](/booking)** — reunion energy, photos, no phones on the water. Full day pontoon or [sunset cruise](/experiences/sunset) if you're here only a weekend." },
      { type: "h2", content: "48-Hour LDR Itinerary" },
      { type: "ul", items: ["Day 1 arrival: quiet dinner, early night", "Day 2: boat + favorite neighborhood", "Day 3: brunch, one more favorite spot, depart"] },
      { type: "p", content: "See [weekend getaway](/blog/austin-weekend-getaway-couples-itinerary). [Book boat now](/booking) — limited weekends fill." },
    ],
    relatedLinks: [PILLAR, BOOKING, SUNSET, PONTOON, { href: "/blog/austin-weekend-getaway-couples-itinerary", text: "Weekend itinerary", external: false }],
  },
  // #25
  {
    slug: "austin-group-date-ideas",
    title: "Austin Group Date Ideas: Fun Things to Do With Other Couples",
    excerpt: "Double date and group date ideas in Austin — pontoon charters for up to 14 guests, breweries, and lake days that beat awkward dinner tables.",
    date: "2026-04-25",
    author: "Boat Bros",
    image: "/photos/IMG_1197.webp",
    imageAlt: "Group date on Lake Austin pontoon",
    category: "general",
    readingTimeMinutes: 8,
    seoKeywords: ["group date ideas Austin", "double date ideas Austin", "Austin activities for couples groups", "group date Austin", "pontoon group date Austin"],
    keyTakeaways: ["Pontoon charter fits double dates and friend groups up to ~14.", "Split cost makes lake day affordable per couple.", "BYO snacks, playlist, soft coolers — no glass.", "Book captain so nobody drives.", "Combine with brewery or taco after dock."],
    faqs: [{ q: "What is a good double date in Austin?", a: "Captained Lake Austin pontoon — shared activity, room to spread out, built-in conversation and swimming." }],
    body: [
      { type: "p", content: "Group dates in Austin work when there's **something to do**, not just four people staring over entrees. Enter the pontoon. [50 date ideas](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "Best Group Date: Lake Austin Pontoon" },
      { type: "p", content: "[Pontoon charter](/experiences/lake-austin-pontoon) — up to 14 guests, captain included. Swim cove, music, coolers." },
      { type: "h2", content: "More Group Ideas" },
      { type: "ul", items: ["Escape room + drinks", "Meanwhile Brewing yard", "Topgolf or bat watching", "Cooking class for four", "Sunset cruise tickets if smaller group"] },
      { type: "p", content: "[Book group pontoon](/booking)." },
    ],
    relatedLinks: [PILLAR, BOOKING, PONTOON, AUSTIN_RENTAL, { href: "/blog/austin-couples-activities", text: "Couples activities", external: false }],
  },
  // #26
  {
    slug: "special-date-night-austin-budget",
    title: "How to Make Any Date Night in Austin Feel Special (Even on a Budget)",
    excerpt: "Romantic Austin date nights on a budget — sunset cruises from $35, thoughtful details, and how to feel premium without premium prices.",
    date: "2026-04-24",
    author: "Boat Bros",
    image: "/photos/IMG_9647%202.webp",
    imageAlt: "Affordable special date night Lake Austin sunset",
    category: "general",
    readingTimeMinutes: 8,
    seoKeywords: ["special date night Austin", "romantic date night Austin budget", "Austin date night tips", "make date night special Austin", "cheap romantic dates Austin"],
    keyTakeaways: ["Intention beats spend: playlist, note, planned timing.", "Sunset cruise from $35 = affordable luxury.", "Free: Bonnell, boardwalk, home cooked meal.", "Put phones away 2 hours minimum.", "One planned surprise detail changes everything."],
    faqs: [{ q: "How do you make a date night special in Austin on a budget?", a: "Book a sunset cruise, write a short note, and plan one surprise detail — quality time on the lake beats expensive restaurants." }],
    body: [
      { type: "p", content: "Special date night Austin doesn't require a black card — it requires you showing up on purpose. [50 date ideas](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "Affordable Luxury" },
      { type: "p", content: "**[Sunset cruise from $35](/booking)** — captained, scenic, feels splurgy. See [no-reservation dates](/blog/austin-date-night-no-reservation)." },
      { type: "h2", content: "Free & Low-Cost Touches" },
      { type: "ul", items: ["Handwritten note", "Their favorite snack packed", "Sunset walk before or after boat", "Curated playlist in the car", "Starbucks walk + real conversation"] },
      { type: "p", content: "Be the partner who plans — [book sunset](/booking)." },
    ],
    relatedLinks: [PILLAR, BOOKING, SUNSET, { href: "/blog/austin-date-night-no-reservation", text: "Date night without reservations", external: false }],
  },
  // #27
  {
    slug: "austin-experiences-worth-the-hype",
    title: "Austin Experiences That Are Actually Worth the Hype",
    excerpt: "Which Austin experiences deliver vs. disappoint — including the Lake Austin boat cruise that consistently exceeds expectations.",
    date: "2026-04-23",
    author: "Boat Bros",
    image: "/photos/IMG_1197.webp",
    imageAlt: "Lake Austin experience worth the hype",
    category: "general",
    readingTimeMinutes: 8,
    seoKeywords: ["Austin experiences worth the hype", "best Austin experiences", "overhyped Austin things", "Austin bucket list", "worth it Austin"],
    keyTakeaways: ["Lake Austin captained cruise consistently delivers — worth the hype.", "Some BBQ lines exceed value — go off-peak or local spots.", "Barton Springs lives up to it — go early.", "Plan experiences with logistics handled (captain).", "Boat beats viral restaurant if you want memories."],
    faqs: [{ q: "Is a Lake Austin boat cruise worth the hype?", a: "Yes — especially captained sunset and pontoon days. Reviews consistently cite it as the highlight of Austin trips." }],
    body: [
      { type: "p", content: "Austin hype is loud. These experiences actually deliver — **boat on Lake Austin** leads the list. [Bucket list](/blog/austin-bucket-list-couples) | [50 dates](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "Worth the Hype" },
      { type: "ul", items: ["Lake Austin sunset cruise & pontoon", "Barton Springs (early)", "Live music at Continental / Antone's", "Tacos on Veracruz / Valentina's", "Congress Bridge bats (seasonal)"] },
      { type: "h2", content: "Depends on Timing" },
      { type: "p", content: "Famous BBQ lines, Rainey on Saturday midnight — great with expectations managed." },
      { type: "p", content: "[Book the experience that delivers](/booking) | [Honest boat rental review](/blog/is-boat-rental-austin-worth-it)." },
    ],
    relatedLinks: [PILLAR, BOOKING, SUNSET, { href: "/blog/is-boat-rental-austin-worth-it", text: "Is boat rental worth it?", external: false }, { href: "/blog/austin-bucket-list-couples", text: "Couples bucket list", external: false }],
  },
  // #28
  {
    slug: "special-occasion-austin-ideas",
    title: "What to Do in Austin for a Special Occasion (Beyond the Usual)",
    excerpt: "Celebrate birthdays, promotions, and milestones in Austin — private charters and experiences beyond another dinner reservation.",
    date: "2026-04-22",
    author: "Boat Bros",
    image: "/photos/IMG_1197.webp",
    imageAlt: "Special occasion celebration on Lake Austin",
    category: "general",
    readingTimeMinutes: 8,
    seoKeywords: ["special occasion Austin", "Austin special occasion ideas", "celebrate in Austin", "Austin milestone experiences", "birthday celebration Austin couples"],
    keyTakeaways: ["Match experience to occasion — sunset for birthdays, private charter for big milestones.", "Tell operator the occasion for discretion/help.", "Combine 2 beats max: boat + dinner.", "Valentine's and NYE book early.", "Private charter is go-to for any special occasion."],
    faqs: [{ q: "How do you celebrate a special occasion in Austin?", a: "Book a private Lake Austin charter or sunset cruise, then one favorite meal — keep the focus on the experience." }],
    body: [
      { type: "p", content: "Special occasion in Austin? Skip the usual steakhouse-only plan. **[Private charter](/booking)** works for birthdays, promotions, reconciliations, and \"just because.\" [Milestones map](/blog/relationship-milestones-austin-couples) | [50 dates](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "By Occasion" },
      { type: "ul", items: ["Birthday: pontoon + cake on water", "Promotion: luxury dinner + [sunset](/experiences/sunset)", "Reunion: [LDR guide](/blog/long-distance-relationship-austin-visit)", "Engagement: [proposal boat](/blog/how-to-propose-on-a-boat-austin)"] },
      { type: "p", content: "[Book special occasion charter](/booking)." },
    ],
    relatedLinks: [PILLAR, BOOKING, PONTOON, { href: "/blog/relationship-milestones-austin-couples", text: "Relationship milestones", external: false }, { href: "/blog/luxury-date-ideas-austin", text: "Luxury date ideas", external: false }],
  },
  // #29 — Relationship milestones (full brief)
  {
    slug: "relationship-milestones-austin-couples",
    title: "Austin Relationship Milestones: How to Celebrate Every Stage Memorably",
    excerpt: "From first dates to proposals and anniversaries — how Austin couples celebrate every relationship milestone with the right experience.",
    date: "2026-04-21",
    author: "Boat Bros",
    image: "/photos/IMG_9647%202.webp",
    imageAlt: "Celebrating relationship milestones on Lake Austin",
    category: "general",
    readingTimeMinutes: 11,
    seoKeywords: ["relationship milestones Austin", "celebrate anniversary Austin", "Austin milestone ideas", "relationship celebration Austin", "couples milestones Austin TX"],
    keyTakeaways: ["First months: low-pressure dates, then sunset cruise wow.", "One year+: pontoon or private charter anniversary.", "Proposal: private Lake Austin boat — see proposal guides.", "Engagement: pontoon party with friends.", "Married milestones: repeat boat tradition annually."],
    faqs: [
      { q: "How do Austin couples celebrate anniversaries?", a: "Many book a Lake Austin sunset cruise or private charter — repeatable tradition with captained logistics." },
      { q: "What experience fits a first anniversary in Austin?", a: "Sunset cruise or half-day pontoon; upgrade to private charter for 5th+ years." },
    ],
    body: [
      { type: "p", content: "Relationship milestones in Austin map cleanly to experiences — here's the playbook. Pillar: [50 best date ideas](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "First Dates & First 3 Months" },
      { type: "p", content: "Coffee, walks, food trucks — then [sunset cruise](/experiences/sunset) when ready. [New couples guide](/blog/date-ideas-new-couples-austin)." },
      { type: "h2", content: "Six Months to One Year" },
      { type: "p", content: "[Pontoon day](/experiences/lake-austin-pontoon) or [unique date](/blog/unique-date-ideas-austin). **Celebrate with a [sunset cruise](/booking).**" },
      { type: "h2", content: "Proposal" },
      { type: "p", content: "**[Book private proposal charter](/booking)** — [how to propose on a boat](/blog/how-to-propose-on-a-boat-austin) | [plan proposal](/blog/how-to-plan-marriage-proposal-austin)." },
      { type: "h2", content: "Engagement & Wedding Season" },
      { type: "p", content: "[Engagement party on the lake](/blog/engagement-party-austin). Engagement photos optional on charter." },
      { type: "h2", content: "Anniversaries & Long-Term" },
      { type: "p", content: "[Anniversary ideas by budget](/blog/best-anniversary-ideas-austin) | [luxury tier](/blog/luxury-date-ideas-austin). Make the boat an annual tradition." },
      { type: "h2", content: "Whatever the Milestone" },
      { type: "p", content: "[Book your milestone experience](/booking) — we'll help make it unforgettable." },
    ],
    relatedLinks: [PILLAR, BOOKING, SUNSET, { href: "/blog/how-to-plan-marriage-proposal-austin", text: "Marriage proposal planning", external: false }, { href: "/blog/best-anniversary-ideas-austin", text: "Anniversary ideas", external: false }, { href: "/blog/luxury-date-ideas-austin", text: "Luxury date ideas", external: false }],
  },
  // #30 — Worth it review (full brief)
  {
    slug: "is-boat-rental-austin-worth-it",
    title: "Is a Boat Rental in Austin Worth It? An Honest Answer (From the People Who Run Them)",
    excerpt: "Wondering if a Lake Austin boat rental is worth the cost? Honest breakdown of what you get, what it costs, and whether it's right for your date or group.",
    date: "2026-04-20",
    author: "Boat Bros",
    image: "/photos/IMG_1197.webp",
    imageAlt: "Lake Austin boat rental — honest review",
    category: "boat-tips",
    readingTimeMinutes: 9,
    seoKeywords: ["boat rental Austin worth it", "is Lake Austin boat rental worth it", "Austin boat rental review", "Lake Austin boat rental cost", "worth it boat rental Austin"],
    keyTakeaways: [
      "Worth it when: captained, group splits cost, or milestone date/proposal.",
      "Sunset tickets from $35 are lowest-risk way to test the lake.",
      "DIY rental saves money but adds captain stress — often false economy for dates.",
      "Compare to dinner+show in Austin — boat often wins on memory per dollar.",
      "Not worth it if: no one wants sun/water, or you won't book ahead on peak weekends.",
    ],
    faqs: [
      { q: "Is a Lake Austin boat rental worth the money?", a: "For most couples and groups, yes — especially captained experiences where you relax instead of driving. Sunset cruises are the most affordable entry point." },
      { q: "How much does a boat rental cost in Austin?", a: "Sunset cruises can start around $35/ticket; private pontoon charters vary by duration and date. Check current pricing when you book." },
      { q: "Should I rent with or without a captain?", a: "For dates, proposals, and parties, captained is worth it. Experienced boaters doing a casual swim day may skipper themselves if licensed and comfortable." },
    ],
    body: [
      { type: "p", content: "We're Boat Bros — we run [Lake Austin rentals](/austin-boat-rental) daily. Here's an honest answer to **is a boat rental in Austin worth it?** No hype, just what we see work and what doesn't. [50 date ideas](/blog/50-best-date-ideas-austin)." },
      { type: "h2", content: "When It's Absolutely Worth It" },
      { type: "ul", items: ["Proposals and anniversaries — privacy and scenery you can't replicate", "Groups splitting a pontoon — cost per person drops fast", "Visitors with one weekend — maximize Austin memory", "Anyone who wants captained = zero stress"] },
      { type: "h2", content: "When to Start Smaller" },
      { type: "p", content: "Try **[sunset cruise from $35](/experiences/sunset)** before a full-day charter. Read [sunset cruise guide](/blog/austin-sunset-cruise-guide)." },
      { type: "h2", content: "Cost vs. Dinner & a Show" },
      { type: "p", content: "Two dinners + activities often exceed one boat day — but only the boat becomes the story you retell for years." },
      { type: "h2", content: "When It Might Not Be Worth It" },
      { type: "p", content: "You hate sun, get seasick on calm water (rare here), or refuse to book ahead on July 4th weekend then blame availability." },
      { type: "h2", content: "Still Not Sure?" },
      { type: "p", content: "Text us — we'll help you figure out if it's the right fit. Or [check availability](/booking) for sunset tickets. Trust-first: we'd rather you book the right experience than any experience." },
    ],
    relatedLinks: [PILLAR, AUSTIN_RENTAL, BOOKING, SUNSET, { href: "/experiences", text: "All experiences", external: false }, { href: "/blog/austin-sunset-cruise-guide", text: "Sunset cruise guide", external: false }],
  },
];
